spring:
  flyway:
    enabled: false
  datasource:
    hikari:
      # Do not fail application startup if DB is unreachable
      initialization-fail-timeout: 0
      # Keep timeouts short during dev
      connection-timeout: 3000
  jpa:
    # Defer DB touch until actually needed
    defer-datasource-initialization: true
    properties:
      # Avoid aggressive metadata access at startup
      hibernate.temp.use_jdbc_metadata_defaults: true

logging:
  level:
    org.springframework.jdbc: WARN
    org.flywaydb.core: WARN

